export const SHOW_TICKET_INPUT_FORM = 'SHOW_TICKET_INPUT_FORM' as const;
export const HIDE_TICKET_INPUT_FORM = 'HIDE_TICKET_INPUT_FORM' as const;

export const POST_ADD_TICKET_REQUEST = 'POST_ADD_TICKET_REQUEST' as const;
export const POST_ADD_TICKET_SUCCESS = 'POST_ADD_TICKET_SUCCESS' as const;

export const GET_SEARCH_POSTER_REQUEST = 'GET_SEARCH_POSTER_REQUEST' as const;
export const GET_SEARCH_POSTER_SUCCESS = 'GET_SEARCH_POSTER_SUCCESS' as const;
