export const GET_STATISTICS_ACTOR_REQUEST = 'GET_STATISTICS_ACTOR_REQUEST' as const;
export const GET_STATISTICS_ACTOR_SUCCESS = 'GET_STATISTICS_ACTOR_SUCCESS' as const;

export const GET_STATISTICS_VIEW_REQUEST = 'GET_STATISTICS_VIEW_REQUEST' as const;
export const GET_STATISTICS_VIEW_SUCCESS = 'GET_STATISTICS_VIEW_SUCCESS' as const;
