export const GET_ALL_TICKETS_REQUEST = 'GET_ALL_TICKETS_REQUEST' as const;
export const GET_ALL_TICKETS_SUCCESS = 'GET_ALL_TICKETS_SUCCESS' as const;

export const GET_UPCOMING_TICKETS_REQUEST = 'GET_UPCOMING_TICKETS_REQUEST' as const;
export const GET_UPCOMING_TICKETS_SUCCESS = 'GET_UPCOMING_TICKETS_SUCCESS' as const;
